#! /usr/bin/env php
<?php 
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

define('BASE_DIR', __DIR__);

// require BASE_DIR.'/vendor/autoload.php'; # for local testing
require BASE_DIR.'/../../autoload.php'; # for production

$app = new Application('Steve - Luís Dalmolin personal Minion', '0.1.0');
$app->add(new Dalmolin\Console\NginxAddSiteCommand);
$app->run();